# Generated by Django 4.0.3 on 2022-03-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_series', models.IntegerField()),
                ('card_number', models.IntegerField()),
                ('card_issue_date', models.DateTimeField()),
                ('last_date_of', models.DateTimeField()),
                ('date_of_use', models.DateTimeField(auto_now_add=True)),
                ('summa', models.IntegerField()),
                ('card_status', models.CharField(choices=[('not_activated', 'Not Activated'), ('activated', 'Activated'), ('expired', 'Expired')], default='not_activated', max_length=50)),
                ('is_active_card', models.BooleanField(default=False)),
            ],
        ),
    ]
